source 'https://rubygems.org'

# test
gem 'rspec'

# pry
gem 'pry'
gem 'pry-doc'
gem 'pry-nav'
# gem 'pry-coolline'

# rails
gem 'rails'
gem 'spring'

# web services
gem 'aws-sdk'
gem 'travis'

gem 'nfc'
gem 'parallel'
