source :rubygems

# test
gem 'rspec'
gem 'cucumber'
gem 'spork', '~> 1.0rc'

# pry
gem 'pry'
gem 'pry-doc'
gem 'pry-nav'
# gem 'pry-coolline'

# rails
gem 'rails', '~> 3.2.0'

# web services
gem 'aws-sdk'
