git_branch() {
    __git_ps1 '(git:%s)'
}
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(git_branch)\n\$ '

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias be="bundle exec"
alias r="rails"

git_cd() {
    path="`git rev-parse --git-dir`/../$1"
    ret=$?
    if [ ${ret} -eq 0 ]; then cd ${path}; fi
}
alias gcd="git_cd"

export PATH=$HOME/bin:/usr/local/bin/:$PATH
export PATH=$PATH:/usr/local/texlive/2013basic/bin/x86_64-darwin/
